services:
  web:
    image: openjdk:17
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./spring:/srv:cached
    working_dir: /srv
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./psql:/var/lib/postgresql/data
